/**
 * Seed biography content — conforms to the Biography domain model
 * (lib/types/domain.ts). This is the design-approved content; wording
 * should not change without sign-off. Structure exactly mirrors what the
 * Supabase `legends` + `timeline_events` + `quotes` + `gallery_images`
 * tables will hold, so this file is a drop-in replacement target, not a
 * parallel shape.
 */
import type { Biography } from '@/lib/types/domain';

/** Backward-compatible alias — components importing `Legend` continue to work unchanged. */
export type Legend = Biography;

const SITE_URL = 'https://lifelegends.example';

export const seedLegends: Biography[] = [
  {
    slug: 'tesla',
    name: 'Nikola Tesla',
    roles: ['Inventor', 'Engineer', 'Futurist'],
    birthYear: 1856,
    deathYear: 1943,
    nationality: 'Serbian-American',
    profession: 'Electrical Engineer',
    tagline: '"The Man Who Lit Up the World."',
    intro: 'A visionary inventor and electrical engineer who revolutionized the modern world with alternating current, wireless energy, and futuristic ideas decades ahead of his time.',
    heroImage: 'https://commons.wikimedia.org/wiki/Special:FilePath/Nikola%20Tesla%20by%20Sarony%20c1898.jpg?width=1400',
    thumbnail: 'https://commons.wikimedia.org/wiki/Special:FilePath/Nikola%20Tesla%20by%20Sarony%20c1898.jpg?width=600',
    categorySlug: 'inventors',
    featured: true,
    viewCount: 25600,
    status: 'published',
    overviewTitle: 'A Mind Ahead of Its Century',
    overview: [
      'Born in 1856 in Smiljan, in the Austrian Empire, Nikola Tesla would go on to hold hundreds of patents across a dozen countries, laying the groundwork for the alternating-current systems that power the modern world.',
      'After studying engineering in Graz and Prague, Tesla emigrated to the United States in 1884 with little more than a letter of introduction and a head full of ideas that would soon reshape how humanity generated, transmitted, and used electricity.',
      "His rivalry with Thomas Edison over AC versus DC power, his radical wireless-energy experiments at Wardenclyffe, and his lifelong pursuit of ideas the world wasn't yet ready for have made him one of history's most enduring symbols of visionary genius.",
    ],
    stats: [
      { value: 700, label: 'Patents' }, { value: 300, label: 'Inventions' },
      { value: 26, label: 'Countries' }, { value: '∞', label: 'Impact' },
    ],
    timeline: [
      { year: 1856, title: 'Born in Smiljan', description: 'Nikola Tesla is born in the village of Smiljan, in the Austrian Empire (present-day Croatia).' },
      { year: 1875, title: 'Studies at Graz University', description: 'Enrolls to study electrical engineering, where he first conceives the idea of a rotating magnetic field.' },
      { year: 1884, title: 'Moves to the United States', description: 'Arrives in New York with a letter of introduction to Thomas Edison and four cents in his pocket.' },
      { year: 1891, title: 'Patents the AC Induction Motor', description: 'His polyphase alternating-current system becomes the foundation of modern power distribution.' },
      { year: 1893, title: "Chicago World's Fair", description: 'Demonstrates AC power on a grand public stage, helping win the "War of Currents."' },
      { year: 1943, title: 'Passes Away in New York', description: 'Dies alone in a New York hotel room, leaving behind a legacy that would only grow with time.' },
    ],
    achievements: [
      { counter: 700, title: 'Patents Filed', description: 'Across the US, Europe, and beyond, spanning motors, wireless transmission, and lighting.' },
      { counter: 'AC', title: 'Polyphase System', description: 'His AC induction motor became the backbone of modern electrical power distribution.' },
      { counter: 1943, title: 'Enduring Legacy', description: 'Honored posthumously with the SI unit of magnetic flux density, the tesla (T).' },
    ],
    quotes: [{ text: '"The present is theirs; the future, for which I really worked, is mine."', attribution: 'Nikola Tesla', featured: true }],
    gallery: [
      { url: 'https://commons.wikimedia.org/wiki/Special:FilePath/Nikola%20Tesla%2C%20circa%201890.jpeg?width=700', alt: 'Nikola Tesla, circa 1890' },
      { url: 'https://commons.wikimedia.org/wiki/Special:FilePath/Tesla%20Wardenclyffe%201904.jpg?width=500', alt: 'Wardenclyffe Tower, 1904' },
      { url: 'https://commons.wikimedia.org/wiki/Special:FilePath/Nikola%20Tesla%20by%20Sarony%20c1898.jpg?width=500', alt: 'Nikola Tesla studio portrait, c. 1898' },
      { url: 'https://commons.wikimedia.org/wiki/Special:FilePath/N.Tesla.JPG?width=500', alt: 'Nikola Tesla portrait' },
    ],
    facts: [
      { summary: 'Tesla could allegedly speak eight languages fluently.', expand: 'He was fluent in Serbian, English, Czech, German, French, Hungarian, Italian, and Latin, and claimed an eidetic memory that let him visualize entire inventions in his mind before ever building a prototype.' },
      { summary: 'He envisioned global wireless communication decades early.', expand: "His Wardenclyffe Tower project aimed to transmit information — and eventually free electrical power — wirelessly across the globe, a concept not fully realized until Wi-Fi and cellular networks over a century later." },
      { summary: 'Tesla never married, citing his work as his true devotion.', expand: 'He often said celibacy helped him focus entirely on his inventions, and was known for close friendships instead — including a well-documented fondness for the pigeons he fed daily in New York parks.' },
      { summary: 'He died with 300+ patents but in financial hardship.', expand: "Despite his enormous scientific output, Tesla's later-life projects struggled to find funding, and he died in 1943 in a modest New York hotel room — full recognition largely arrived decades after his death." },
    ],
    sources: [
      { name: 'Smithsonian Institution', description: 'Archival biography' },
      { name: 'IEEE History Center', description: 'Engineering legacy review' },
      { name: 'Tesla Science Center at Wardenclyffe', description: 'Primary source materials' },
    ],
    seo: { metaTitle: 'Nikola Tesla | LifeLegends', metaDescription: 'Discover the life of Nikola Tesla, the inventor who electrified the modern world.', canonicalPath: '/legends/tesla', ogImage: `${SITE_URL}/og/tesla.jpg` },
  },
  {
    slug: 'einstein',
    name: 'Albert Einstein',
    roles: ['Physicist', 'Theorist', 'Nobel Laureate'],
    birthYear: 1879,
    deathYear: 1955,
    nationality: 'German-American',
    profession: 'Theoretical Physicist',
    tagline: '"Imagination is more important than knowledge."',
    intro: "A theoretical physicist whose theory of relativity reshaped humanity's understanding of space, time, and gravity, and whose name became a global synonym for genius.",
    heroImage: 'https://commons.wikimedia.org/wiki/Special:FilePath/Albert%20Einstein%20Head.jpg?width=1400',
    thumbnail: 'https://commons.wikimedia.org/wiki/Special:FilePath/Albert%20Einstein%20Head.jpg?width=600',
    categorySlug: 'scientists',
    featured: true,
    viewCount: 17800,
    status: 'published',
    overviewTitle: 'The Architect of Relativity',
    overview: [
      'Born in Ulm, Germany in 1879, Albert Einstein showed early fascination with mathematics and physics, though his unconventional thinking often put him at odds with formal schooling.',
      'While working as a patent clerk in Switzerland, Einstein published four papers in 1905 — his "miracle year" — that would transform physics, including the special theory of relativity and the equation E=mc².',
      'His general theory of relativity, published in 1915, redefined gravity itself, and observational confirmation in 1919 made him an international celebrity almost overnight.',
    ],
    stats: [
      { value: 300, label: 'Papers Published' }, { value: 1921, label: 'Nobel Prize' },
      { value: 4, label: 'Fields Advanced' }, { value: '∞', label: 'Impact' },
    ],
    timeline: [
      { year: 1879, title: 'Born in Ulm, Germany', description: 'Albert Einstein is born into a middle-class Jewish family in the German Empire.' },
      { year: 1900, title: 'Graduates ETH Zurich', description: 'Completes his teaching diploma in physics and mathematics.' },
      { year: 1905, title: 'The Miracle Year', description: 'Publishes four groundbreaking papers, including special relativity, while working at the Swiss patent office.' },
      { year: 1915, title: 'General Theory of Relativity', description: 'Presents a new understanding of gravity as the curvature of spacetime.' },
      { year: 1921, title: 'Wins the Nobel Prize in Physics', description: 'Awarded for his explanation of the photoelectric effect.' },
      { year: 1955, title: 'Passes Away in Princeton', description: 'Dies in Princeton, New Jersey, having become the most recognized scientist of the 20th century.' },
    ],
    achievements: [
      { counter: 1921, title: 'Nobel Prize in Physics', description: 'Awarded for his explanation of the photoelectric effect, foundational to quantum theory.' },
      { counter: 'E=mc²', title: 'Mass-Energy Equivalence', description: 'One of the most famous equations in the world, linking mass and energy.' },
      { counter: 1915, title: 'General Relativity', description: 'Redefined gravity as the curvature of spacetime, confirmed observationally in 1919.' },
    ],
    quotes: [{ text: '"Imagination is more important than knowledge."', attribution: 'Albert Einstein', featured: true }],
    gallery: [
      { url: 'https://commons.wikimedia.org/wiki/Special:FilePath/Albert%20Einstein%20Head.jpg?width=700', alt: 'Albert Einstein portrait' },
      { url: 'https://commons.wikimedia.org/wiki/Special:FilePath/Einstein_1921_by_F_Schmutzer_-_restoration.jpg?width=500', alt: 'Albert Einstein, 1921' },
    ],
    facts: [
      { summary: 'Einstein was offered the presidency of Israel in 1952.', expand: 'He respectfully declined, saying he lacked the natural aptitude and experience to deal with human problems the way he could deal with the laws of physics.' },
      { summary: "He did not fail math as a student — that's a myth.", expand: 'Einstein excelled at mathematics from a young age; the popular story of him failing school math is false and likely originated from a misunderstanding of European grading scales.' },
      { summary: 'His brain was preserved for scientific study after death.', expand: "Without his family's initial permission, a pathologist removed and preserved Einstein's brain, hoping future science might locate the source of his genius." },
    ],
    sources: [
      { name: 'Nobel Prize Organization', description: 'Official biography and prize record' },
      { name: 'Princeton University Archives', description: 'Personal papers collection' },
      { name: 'American Institute of Physics', description: 'Historical record' },
    ],
    seo: { metaTitle: 'Albert Einstein | LifeLegends', metaDescription: "Discover the life of Albert Einstein, architect of the theory of relativity.", canonicalPath: '/legends/einstein', ogImage: `${SITE_URL}/og/einstein.jpg` },
  },
  {
    slug: 'curie',
    name: 'Marie Curie',
    roles: ['Physicist', 'Chemist', 'Nobel Laureate'],
    birthYear: 1867,
    deathYear: 1934,
    nationality: 'Polish-French',
    profession: 'Physicist & Chemist',
    tagline: '"Nothing in life is to be feared, it is only to be understood."',
    intro: 'A pioneering physicist and chemist whose research on radioactivity made her the first person to win Nobel Prizes in two different sciences.',
    heroImage: 'https://commons.wikimedia.org/wiki/Special:FilePath/Marie%20Curie%201903.jpg?width=1400',
    thumbnail: 'https://commons.wikimedia.org/wiki/Special:FilePath/Marie%20Curie%201903.jpg?width=600',
    categorySlug: 'scientists',
    featured: true,
    viewCount: 19200,
    status: 'published',
    overviewTitle: 'Illuminating the Invisible',
    overview: [
      'Born Maria Skłodowska in Warsaw in 1867, Marie Curie moved to Paris to pursue studies denied to women in Russian-controlled Poland, enrolling at the Sorbonne.',
      'Alongside her husband Pierre, she discovered the elements polonium and radium, coining the term "radioactivity" and laying the foundation for a new field of physics and chemistry.',
      'Her work came at great personal cost — prolonged radiation exposure would eventually contribute to her death — but it revolutionized medicine, physics, and our understanding of the atom.',
    ],
    stats: [
      { value: 2, label: 'Nobel Prizes' }, { value: 2, label: 'Elements Discovered' },
      { value: 1, label: 'First Woman Professor, Sorbonne' }, { value: '∞', label: 'Impact' },
    ],
    timeline: [
      { year: 1867, title: 'Born in Warsaw, Poland', description: 'Born Maria Skłodowska under Russian occupation, where women were barred from higher education.' },
      { year: 1891, title: 'Moves to Paris', description: 'Enrolls at the Sorbonne to study physics and mathematics.' },
      { year: 1898, title: 'Discovers Polonium and Radium', description: 'With husband Pierre Curie, isolates two new radioactive elements.' },
      { year: 1903, title: 'First Nobel Prize', description: 'Shares the Nobel Prize in Physics for research on radioactivity.' },
      { year: 1911, title: 'Second Nobel Prize', description: 'Wins the Nobel Prize in Chemistry, becoming the first person to win in two sciences.' },
      { year: 1934, title: 'Passes Away', description: 'Dies from aplastic anemia, likely caused by prolonged radiation exposure.' },
    ],
    achievements: [
      { counter: 2, title: 'Nobel Prizes', description: 'The first person in history to win Nobel Prizes in two different scientific fields.' },
      { counter: 'Ra & Po', title: 'Elements Discovered', description: 'Isolated radium and polonium, founding the study of radioactivity.' },
      { counter: 1, title: 'First Woman Professor', description: 'Became the first female professor at the University of Paris.' },
    ],
    quotes: [{ text: '"Nothing in life is to be feared, it is only to be understood."', attribution: 'Marie Curie', featured: true }],
    gallery: [
      { url: 'https://commons.wikimedia.org/wiki/Special:FilePath/Marie%20Curie%201903.jpg?width=700', alt: 'Marie Curie, 1903' },
    ],
    facts: [
      { summary: 'Her research notebooks are still radioactive today.', expand: "Curie's papers and belongings are so contaminated with radium-226 that they are kept in lead-lined boxes at the French National Library, and visitors must sign a waiver and wear protective gear to view them." },
      { summary: 'She created mobile X-ray units during World War I.', expand: 'Dubbed "petites Curies," these mobile radiography units helped treat wounded soldiers on the battlefield, and Curie personally trained women to operate them.' },
      { summary: 'She remains the only person with Nobels in two sciences.', expand: 'No one else in history has won Nobel Prizes in two different scientific disciplines — physics and chemistry.' },
    ],
    sources: [
      { name: 'Nobel Prize Organization', description: 'Official biography and prize record' },
      { name: 'Curie Museum, Paris', description: 'Institut Curie archival collection' },
      { name: 'French National Library', description: 'Personal papers and notebooks' },
    ],
    seo: { metaTitle: 'Marie Curie | LifeLegends', metaDescription: 'Discover the life of Marie Curie, pioneer of radioactivity research.', canonicalPath: '/legends/curie', ogImage: `${SITE_URL}/og/curie.jpg` },
  },
  {
    slug: 'davinci',
    name: 'Leonardo da Vinci',
    roles: ['Artist', 'Inventor', 'Polymath'],
    birthYear: 1452,
    deathYear: 1519,
    nationality: 'Italian',
    profession: 'Artist & Inventor',
    tagline: '"Simplicity is the ultimate sophistication."',
    intro: 'A Renaissance polymath whose paintings, anatomical studies, and visionary engineering sketches made him one of the most diversely talented individuals in history.',
    heroImage: 'https://commons.wikimedia.org/wiki/Special:FilePath/Leonardo%20da%20Vinci%20-%20presumed%20self-portrait%20-%20WGA12798.jpg?width=1400',
    thumbnail: 'https://commons.wikimedia.org/wiki/Special:FilePath/Leonardo%20da%20Vinci%20-%20presumed%20self-portrait%20-%20WGA12798.jpg?width=600',
    categorySlug: 'artists',
    featured: false,
    viewCount: 14400,
    status: 'published',
    overviewTitle: 'The Original Renaissance Mind',
    overview: [
      "Born in 1452 in the Tuscan hill town of Vinci, Leonardo apprenticed under the painter Verrocchio in Florence, where his talent quickly outpaced his teacher's.",
      'Beyond his iconic paintings, including the Mona Lisa and The Last Supper, Leonardo filled thousands of notebook pages with anatomical studies, engineering designs, and scientific observations centuries ahead of his time.',
      'He worked across Florence, Milan, and Rome for patrons including the Medici and Sforza families, ultimately dying in France under the patronage of King Francis I.',
    ],
    stats: [
      { value: 20, label: 'Surviving Paintings' }, { value: 7000, label: 'Notebook Pages' },
      { value: 3, label: 'Italian City-States' }, { value: '∞', label: 'Impact' },
    ],
    timeline: [
      { year: 1452, title: 'Born in Vinci, Tuscany', description: 'Born out of wedlock to a notary and a peasant woman near Florence.' },
      { year: 1466, title: 'Apprentices under Verrocchio', description: 'Joins the workshop of Andrea del Verrocchio in Florence.' },
      { year: 1482, title: 'Moves to Milan', description: 'Enters the service of Ludovico Sforza as an engineer and artist.' },
      { year: 1495, title: 'Paints The Last Supper', description: 'Completes one of the most reproduced religious paintings in history.' },
      { year: 1503, title: 'Begins the Mona Lisa', description: "Starts work on what would become the world's most famous portrait." },
      { year: 1519, title: 'Passes Away in France', description: 'Dies at Clos Lucé under the patronage of King Francis I.' },
    ],
    achievements: [
      { counter: 'Mona Lisa', title: 'Most Famous Portrait', description: 'Arguably the most recognized painting in the world, housed at the Louvre.' },
      { counter: 7000, title: 'Notebook Pages', description: 'Surviving pages of anatomical, engineering, and scientific studies.' },
      { counter: 'Polymath', title: 'Renaissance Ideal', description: 'Mastery spanning painting, sculpture, anatomy, engineering, and architecture.' },
    ],
    quotes: [{ text: '"Simplicity is the ultimate sophistication."', attribution: 'Leonardo da Vinci', featured: true }],
    gallery: [
      { url: 'https://commons.wikimedia.org/wiki/Special:FilePath/Leonardo%20da%20Vinci%20-%20presumed%20self-portrait%20-%20WGA12798.jpg?width=700', alt: 'Leonardo da Vinci, presumed self-portrait' },
    ],
    facts: [
      { summary: 'He wrote his notes in mirror-image handwriting.', expand: 'Leonardo, left-handed, wrote right-to-left in reverse script — a habit historians believe helped avoid smudging ink, though it also made his notebooks harder to read casually.' },
      { summary: 'He designed flying machines centuries early.', expand: 'His notebooks contain detailed sketches of ornithopters, parachutes, and other flying contraptions, though none were built or flown in his lifetime.' },
      { summary: 'The Mona Lisa may never have been "finished."', expand: 'Leonardo reportedly kept the painting with him for years, continuing to refine it until his death, rather than delivering it to the patron who commissioned it.' },
    ],
    sources: [
      { name: 'Musée du Louvre', description: 'Painting conservation records' },
      { name: 'Biblioteca Reale di Torino', description: 'Self-portrait provenance' },
      { name: 'Royal Collection Trust', description: 'Notebook and manuscript archive' },
    ],
    seo: { metaTitle: 'Leonardo da Vinci | LifeLegends', metaDescription: 'Discover the life of Leonardo da Vinci, the original Renaissance polymath.', canonicalPath: '/legends/davinci', ogImage: `${SITE_URL}/og/davinci.jpg` },
  },
  {
    slug: 'mandela',
    name: 'Nelson Mandela',
    roles: ['Leader', 'Activist', 'President'],
    birthYear: 1918,
    deathYear: 2013,
    nationality: 'South African',
    profession: 'Anti-Apartheid Leader & President',
    tagline: '"It always seems impossible until it\'s done."',
    intro: "A revolutionary leader and South Africa's first Black president, whose 27 years of imprisonment and lifelong fight against apartheid made him a global symbol of resilience and reconciliation.",
    heroImage: 'https://commons.wikimedia.org/wiki/Special:FilePath/Nelson%20Mandela-2008%20(edit).jpg?width=1400',
    thumbnail: 'https://commons.wikimedia.org/wiki/Special:FilePath/Nelson%20Mandela-2008%20(edit).jpg?width=600',
    categorySlug: 'freedom-fighters',
    featured: true,
    viewCount: 12100,
    status: 'published',
    overviewTitle: 'From Prisoner to President',
    overview: [
      "Born in 1918 in Mvezo, South Africa, Nelson Mandela trained as a lawyer and became a leading figure in the African National Congress's resistance to apartheid.",
      'In 1962 he was arrested and later sentenced to life imprisonment, spending 27 years in prison — most of it on Robben Island — while becoming an international symbol of the anti-apartheid struggle.',
      "Released in 1990, Mandela negotiated the end of apartheid and became South Africa's first democratically elected president in 1994, prioritizing reconciliation over retribution.",
    ],
    stats: [
      { value: 27, label: 'Years Imprisoned' }, { value: 1994, label: 'Elected President' },
      { value: 1993, label: 'Nobel Peace Prize' }, { value: '∞', label: 'Impact' },
    ],
    timeline: [
      { year: 1918, title: 'Born in Mvezo, South Africa', description: 'Born into the Thembu royal family in the Eastern Cape.' },
      { year: 1944, title: 'Joins the African National Congress', description: 'Becomes active in the movement against apartheid policies.' },
      { year: 1962, title: 'Arrested and Imprisoned', description: 'Sentenced to life imprisonment for his role in resistance activities.' },
      { year: 1990, title: 'Released from Prison', description: 'Walks free after 27 years, greeted by global celebration.' },
      { year: 1993, title: 'Awarded the Nobel Peace Prize', description: 'Shares the prize with F.W. de Klerk for dismantling apartheid.' },
      { year: 1994, title: 'Elected President of South Africa', description: "Becomes the country's first democratically elected, Black president." },
    ],
    achievements: [
      { counter: 1993, title: 'Nobel Peace Prize', description: 'Awarded jointly for negotiating the peaceful end of apartheid.' },
      { counter: 1994, title: 'First Black President', description: "Elected in South Africa's first fully democratic election." },
      { counter: 27, title: 'Years of Imprisonment', description: 'Endured decades in prison without abandoning his cause.' },
    ],
    quotes: [{ text: '"It always seems impossible until it\'s done."', attribution: 'Nelson Mandela', featured: true }],
    gallery: [
      { url: 'https://commons.wikimedia.org/wiki/Special:FilePath/Nelson%20Mandela-2008%20(edit).jpg?width=700', alt: 'Nelson Mandela, 2008' },
    ],
    facts: [
      { summary: 'He studied law while in prison on Robben Island.', expand: 'Mandela and fellow prisoners ran what became known as "Robben Island University," educating one another in politics, history, and law during their imprisonment.' },
      { summary: 'He chose reconciliation over revenge as president.', expand: 'Mandela established the Truth and Reconciliation Commission, prioritizing national healing over punishing those responsible for apartheid-era abuses.' },
      { summary: 'His autobiography was partly written in secret.', expand: '"Long Walk to Freedom" was drafted in secret during his imprisonment, with pages smuggled out and hidden by fellow prisoners.' },
    ],
    sources: [
      { name: 'Nelson Mandela Foundation', description: 'Official archives and biography' },
      { name: 'Nobel Prize Organization', description: 'Peace Prize record' },
      { name: 'South African History Archive', description: 'Historical record' },
    ],
    seo: { metaTitle: 'Nelson Mandela | LifeLegends', metaDescription: "Discover the life of Nelson Mandela, from prisoner to president.", canonicalPath: '/legends/mandela', ogImage: `${SITE_URL}/og/mandela.jpg` },
  },
  {
    slug: 'kalam',
    name: 'A. P. J. Abdul Kalam',
    roles: ['Scientist', 'Engineer', 'President'],
    birthYear: 1931,
    deathYear: 2015,
    nationality: 'Indian',
    profession: 'Aerospace Scientist & President',
    tagline: '"Dream, dream, dream. Dreams transform into thoughts, and thoughts result in action."',
    intro: "India's 'Missile Man,' an aerospace scientist who rose from selling newspapers as a boy to leading India's missile and space programs, and later served as the country's 11th President.",
    heroImage: 'https://commons.wikimedia.org/wiki/Special:FilePath/A.%20P.%20J.%20Abdul%20Kalam.jpg?width=1400',
    thumbnail: 'https://commons.wikimedia.org/wiki/Special:FilePath/A.%20P.%20J.%20Abdul%20Kalam.jpg?width=600',
    categorySlug: 'scientists',
    featured: true,
    viewCount: 15300,
    status: 'published',
    overviewTitle: 'From Rameswaram to Rashtrapati Bhavan',
    overview: [
      'Born in 1931 in the temple town of Rameswaram, Tamil Nadu, Avul Pakir Jainulabdeen Abdul Kalam grew up in modest circumstances, selling newspapers to help support his family before pursuing aeronautical engineering.',
      "Kalam became a defining figure in India's space and defense programs, playing a central role in the development of the SLV-III satellite launch vehicle and leading key missile development projects that earned him the nickname 'Missile Man of India.'",
      'In 2002 he was elected the 11th President of India, becoming known as the "People\'s President" for his warmth, humility, and enduring passion for inspiring students — a role he continued even after leaving office, ultimately collapsing while delivering a lecture in 2015.',
    ],
    stats: [
      { value: 1998, label: 'Pokhran-II Tests' }, { value: 2002, label: 'Elected President' },
      { value: 7, label: 'Honorary Doctorates' }, { value: '∞', label: 'Impact' },
    ],
    timeline: [
      { year: 1931, title: 'Born in Rameswaram', description: 'Born into a modest family in Tamil Nadu, India, and sold newspapers as a boy to support his studies.' },
      { year: 1960, title: 'Joins Aeronautical Development', description: 'Begins his career as a scientist at the Aeronautical Development Establishment after studying at the Madras Institute of Technology.' },
      { year: 1980, title: 'Leads SLV-III Launch', description: "Plays a key leadership role in India's first satellite launch vehicle successfully placing a satellite in orbit." },
      { year: 1998, title: 'Pokhran-II Nuclear Tests', description: "Serves as Chief Scientific Adviser during India's series of nuclear tests, cementing his role in national defense." },
      { year: 2002, title: 'Elected President of India', description: 'Becomes the 11th President of India, widely known as the "People\'s President."' },
      { year: 2015, title: 'Passes Away While Teaching', description: 'Collapses and passes away while delivering a lecture to students at IIM Shillong.' },
    ],
    achievements: [
      { counter: 'SLV-III', title: 'Satellite Launch Vehicle', description: 'Led the team behind India\'s first successful satellite launch vehicle.' },
      { counter: 2002, title: '11th President of India', description: 'Served one term as President, celebrated for his accessibility and focus on youth education.' },
      { counter: 'Bharat Ratna', title: "India's Highest Civilian Honor", description: 'Awarded in 1997 for his contributions to science and the nation.' },
    ],
    quotes: [{ text: '"Dream, dream, dream. Dreams transform into thoughts, and thoughts result in action."', attribution: 'A. P. J. Abdul Kalam', featured: true }],
    gallery: [
      { url: 'https://commons.wikimedia.org/wiki/Special:FilePath/A.%20P.%20J.%20Abdul%20Kalam.jpg?width=700', alt: 'A. P. J. Abdul Kalam, official portrait' },
    ],
    facts: [
      { summary: 'He never married, dedicating his life fully to his work.', expand: 'Kalam remained a bachelor throughout his life, living simply and often giving away his belongings and royalties from his books to charitable causes.' },
      { summary: 'He played the veena, a traditional South Indian instrument.', expand: 'Despite his demanding scientific career, Kalam maintained a lifelong love of music and would relax by playing the veena.' },
      { summary: 'He wrote several bestselling books, including Wings of Fire.', expand: 'His autobiography "Wings of Fire" became one of the most widely read books in India, inspiring generations of students toward science and self-belief.' },
    ],
    sources: [
      { name: 'Government of India, Press Information Bureau', description: 'Official biographical record' },
      { name: 'Indian Space Research Organisation (ISRO)', description: 'Institutional history archive' },
      { name: 'Defence Research and Development Organisation (DRDO)', description: 'Program history record' },
    ],
    seo: { metaTitle: 'A. P. J. Abdul Kalam | LifeLegends', metaDescription: "Discover the life of A. P. J. Abdul Kalam, India's Missile Man and the People's President.", canonicalPath: '/legends/kalam', ogImage: `${SITE_URL}/og/kalam.jpg` },
  },
  {
    slug: 'shivaji',
    name: 'Chhatrapati Shivaji Maharaj',
    roles: ['Founder', 'Military Strategist', 'King'],
    birthYear: 1630,
    deathYear: 1680,
    nationality: 'Indian (Maratha)',
    profession: 'Founder of the Maratha Empire',
    tagline: '"Self-respect is the foundation on which all other virtues are built."',
    intro: 'A visionary military strategist and administrator who founded the Maratha Empire in 17th-century India, celebrated for his innovative guerrilla tactics, naval ambitions, and progressive governance.',
    heroImage: 'https://commons.wikimedia.org/wiki/Special:FilePath/Shivaji%20British%20Museum.jpg?width=1400',
    thumbnail: 'https://commons.wikimedia.org/wiki/Special:FilePath/Shivaji%20British%20Museum.jpg?width=600',
    categorySlug: 'politicians',
    featured: false,
    viewCount: 11200,
    status: 'published',
    overviewTitle: 'The Founder of the Maratha Empire',
    overview: [
      'Born in 1630 at the Shivneri Fort in present-day Maharashtra, Shivaji Bhonsale grew up amid the political turbulence of the Deccan, shaped early by his mother Jijabai and his exposure to regional governance and warfare.',
      'Through a combination of daring military campaigns, strategic fort-building, and innovative guerrilla warfare tactics, Shivaji carved out an independent Maratha kingdom in defiance of the much larger Mughal and Bijapur Sultanate forces surrounding him.',
      'In 1674 he was formally crowned Chhatrapati (sovereign) at Raigad Fort, establishing a administration known for its relatively progressive policies, religious tolerance, and early investment in naval power along the western Indian coastline.',
    ],
    stats: [
      { value: 1674, label: 'Crowned Chhatrapati' }, { value: 300, label: 'Forts Held or Built' },
      { value: 50, label: 'Years of Maratha Rule Founded' }, { value: '∞', label: 'Impact' },
    ],
    timeline: [
      { year: 1630, title: 'Born at Shivneri Fort', description: 'Born to Shahaji Bhonsale and Jijabai in the Maval region of present-day Maharashtra.' },
      { year: 1645, title: 'Early Campaigns Begin', description: 'Begins capturing key forts in the Sahyadri hills, laying the foundation of an independent territory.' },
      { year: 1659, title: 'Defeats Afzal Khan', description: 'Defeats the Bijapur Sultanate general Afzal Khan in a decisive and famous encounter at Pratapgad.' },
      { year: 1666, title: 'Escapes Agra Captivity', description: "Famously escapes house arrest under Mughal Emperor Aurangzeb's court in Agra." },
      { year: 1674, title: 'Coronation at Raigad', description: 'Is formally crowned Chhatrapati, establishing the sovereign Maratha kingdom.' },
      { year: 1680, title: 'Passes Away at Raigad', description: 'Dies at Raigad Fort, leaving behind a kingdom that would expand into the Maratha Empire.' },
    ],
    achievements: [
      { counter: 1674, title: 'Coronation as Chhatrapati', description: 'Formally established the Maratha Empire as an independent sovereign kingdom.' },
      { counter: 300, title: 'Fort Network', description: 'Built and fortified an extensive network of hill and coastal forts across western India.' },
      { counter: 'Navy', title: 'Naval Innovation', description: "Built one of early India's first organized naval forces to defend the Konkan coastline." },
    ],
    quotes: [{ text: '"Self-respect is the foundation on which all other virtues are built."', attribution: 'Chhatrapati Shivaji Maharaj', featured: true }],
    gallery: [
      { url: 'https://commons.wikimedia.org/wiki/Special:FilePath/Shivaji%20British%20Museum.jpg?width=700', alt: 'Historical portrait of Shivaji, British Museum collection' },
    ],
    facts: [
      { summary: 'He built one of early India\'s first organized navies.', expand: "Recognizing the strategic importance of the Konkan coastline, Shivaji invested in naval forts and a fleet to defend maritime trade routes from European and other regional powers." },
      { summary: 'His administration is noted for religious tolerance.', expand: 'Contemporary accounts describe Shivaji employing officials from multiple faiths and issuing instructions to his forces to respect mosques, temples, and civilians during military campaigns.' },
      { summary: 'His escape from Agra became a legendary tale.', expand: 'After being placed under house arrest by Emperor Aurangzeb in Agra, Shivaji reportedly escaped by smuggling himself out in a basket of sweets, an episode celebrated in Maratha folklore.' },
    ],
    sources: [
      { name: 'Chhatrapati Shivaji Maharaj Vastu Sangrahalaya', description: 'Museum archival collection, Mumbai' },
      { name: 'Bharat Itihas Sanshodhak Mandal', description: 'Historical research institute record' },
      { name: 'British Museum', description: 'Historical portrait and artifact collection' },
    ],
    seo: { metaTitle: 'Chhatrapati Shivaji Maharaj | LifeLegends', metaDescription: 'Discover the life of Shivaji Maharaj, founder of the Maratha Empire.', canonicalPath: '/legends/shivaji', ogImage: `${SITE_URL}/og/shivaji.jpg` },
  },
  {
    slug: 'gandhi',
    name: 'Mahatma Gandhi',
    roles: ['Leader', 'Activist', 'Philosopher'],
    birthYear: 1869,
    deathYear: 1948,
    nationality: 'Indian',
    profession: 'Independence Leader',
    tagline: '"Be the change that you wish to see in the world."',
    intro: "The leader of India's independence movement, whose philosophy of nonviolent resistance — Satyagraha — inspired civil rights and freedom movements around the world.",
    heroImage: 'https://commons.wikimedia.org/wiki/Special:FilePath/Mahatma-Gandhi%2C%20studio%2C%201931.jpg?width=1400',
    thumbnail: 'https://commons.wikimedia.org/wiki/Special:FilePath/Mahatma-Gandhi%2C%20studio%2C%201931.jpg?width=600',
    categorySlug: 'freedom-fighters',
    featured: true,
    viewCount: 21400,
    status: 'published',
    overviewTitle: 'The Architect of Nonviolent Resistance',
    overview: [
      'Born in 1869 in Porbandar, in present-day Gujarat, Mohandas Karamchand Gandhi trained as a barrister in London before spending over two decades in South Africa, where he first developed his philosophy of nonviolent civil resistance.',
      'Returning to India in 1915, Gandhi became the central figure of the Indian independence movement, mobilizing millions through campaigns of nonviolent non-cooperation, most famously the 1930 Salt March protesting British taxation.',
      "Gandhi's philosophy of Satyagraha — truth-force — went on to directly influence civil rights and independence movements across the world, even as India itself achieved independence in 1947, months before his assassination in January 1948.",
    ],
    stats: [
      { value: 1930, label: 'Salt March' }, { value: 21, label: 'Years in South Africa' },
      { value: 1947, label: "India's Independence" }, { value: '∞', label: 'Impact' },
    ],
    timeline: [
      { year: 1869, title: 'Born in Porbandar', description: 'Born into a Hindu merchant-caste family in the coastal town of Porbandar.' },
      { year: 1893, title: 'Moves to South Africa', description: 'Travels to South Africa for legal work, where he experiences and begins organizing against racial discrimination.' },
      { year: 1915, title: 'Returns to India', description: 'Comes back to India and gradually assumes leadership within the Indian National Congress.' },
      { year: 1930, title: 'Leads the Salt March', description: 'Leads a 240-mile march to the sea to defy the British salt tax, galvanizing national attention.' },
      { year: 1942, title: 'Launches Quit India Movement', description: 'Calls for an end to British rule in India, leading to his arrest along with other leaders.' },
      { year: 1948, title: 'Assassinated in Delhi', description: 'Is assassinated in New Delhi months after India achieves independence.' },
    ],
    achievements: [
      { counter: 'Satyagraha', title: 'Philosophy of Nonviolence', description: 'Developed and popularized nonviolent civil resistance as a tool for political change.' },
      { counter: 1930, title: 'Salt March', description: 'Led one of the most iconic acts of civil disobedience in modern history.' },
      { counter: 1947, title: "India's Independence", description: "Was a central figure in the movement that ended British colonial rule in India." },
    ],
    quotes: [{ text: '"Be the change that you wish to see in the world."', attribution: 'Mahatma Gandhi', featured: true }],
    gallery: [
      { url: 'https://commons.wikimedia.org/wiki/Special:FilePath/Mahatma-Gandhi%2C%20studio%2C%201931.jpg?width=700', alt: 'Mahatma Gandhi, studio portrait, 1931' },
    ],
    facts: [
      { summary: 'He trained as a barrister in London.', expand: 'Gandhi studied law at University College London before beginning his legal career, first in India and then in South Africa.' },
      { summary: 'His South Africa years shaped his entire philosophy.', expand: 'It was during 21 years in South Africa, confronting racial discrimination firsthand, that Gandhi first developed and tested his methods of nonviolent resistance.' },
      { summary: 'He was nominated for the Nobel Peace Prize five times.', expand: 'Despite widespread global recognition of his influence, Gandhi was never awarded the Nobel Peace Prize, a fact the Nobel Committee has since publicly acknowledged as a historical oversight.' },
    ],
    sources: [
      { name: 'Sabarmati Ashram Preservation and Memorial Trust', description: 'Archival and biographical record' },
      { name: 'National Gandhi Museum, New Delhi', description: 'Historical collection' },
      { name: 'Nobel Prize Organization', description: 'Nomination historical record' },
    ],
    seo: { metaTitle: 'Mahatma Gandhi | LifeLegends', metaDescription: "Discover the life of Mahatma Gandhi, leader of India's independence movement.", canonicalPath: '/legends/gandhi', ogImage: `${SITE_URL}/og/gandhi.jpg` },
  },
  {
    slug: 'newton',
    name: 'Isaac Newton',
    roles: ['Physicist', 'Mathematician', 'Astronomer'],
    birthYear: 1643,
    deathYear: 1727,
    nationality: 'English',
    profession: 'Physicist & Mathematician',
    tagline: '"If I have seen further, it is by standing on the shoulders of giants."',
    intro: 'A physicist and mathematician whose laws of motion and universal gravitation, laid out in the Principia Mathematica, became the foundation of classical physics for over two centuries.',
    heroImage: 'https://commons.wikimedia.org/wiki/Special:FilePath/Portrait%20of%20Sir%20Isaac%20Newton%2C%201689.jpg?width=1400',
    thumbnail: 'https://commons.wikimedia.org/wiki/Special:FilePath/Portrait%20of%20Sir%20Isaac%20Newton%2C%201689.jpg?width=600',
    categorySlug: 'scientists',
    featured: false,
    viewCount: 16800,
    status: 'published',
    overviewTitle: 'The Foundation of Classical Physics',
    overview: [
      'Born in 1642 (Old Style calendar) in Woolsthorpe, England, Isaac Newton showed early aptitude for mechanical invention before enrolling at Trinity College, Cambridge.',
      "During a period of plague-driven university closures in the mid-1660s, Newton retreated to his family home, where he laid the groundwork for calculus, optics, and the theory of universal gravitation — a period historians often call his 'year of wonders.'",
      "His 1687 masterwork, the Philosophiæ Naturalis Principia Mathematica, formalized the laws of motion and gravitation, providing the mathematical foundation for classical mechanics that would stand largely unchallenged until Einstein's relativity.",
    ],
    stats: [
      { value: 1687, label: 'Principia Published' }, { value: 3, label: 'Laws of Motion' },
      { value: 1705, label: 'Knighted' }, { value: '∞', label: 'Impact' },
    ],
    timeline: [
      { year: 1643, title: 'Born in Woolsthorpe, England', description: 'Born prematurely, on Christmas Day by the Julian calendar then in use in England.' },
      { year: 1661, title: 'Enrolls at Trinity College, Cambridge', description: 'Begins his studies, initially working as a student servant to fund his education.' },
      { year: 1666, title: 'The Year of Wonders', description: 'Develops foundational ideas in calculus, optics, and gravitation while Cambridge is closed due to plague.' },
      { year: 1687, title: 'Publishes the Principia', description: 'Releases the Philosophiæ Naturalis Principia Mathematica, formalizing the laws of motion and universal gravitation.' },
      { year: 1705, title: 'Knighted by Queen Anne', description: 'Becomes Sir Isaac Newton, one of the first scientists honored in this way.' },
      { year: 1727, title: 'Passes Away in London', description: 'Dies in London and is buried with state honors at Westminster Abbey.' },
    ],
    achievements: [
      { counter: 1687, title: 'Principia Mathematica', description: 'Formalized the three laws of motion and the law of universal gravitation.' },
      { counter: 'Calculus', title: 'Mathematical Foundations', description: 'Independently developed calculus alongside Gottfried Leibniz.' },
      { counter: 'Optics', title: 'Theory of Light', description: "Demonstrated that white light is composed of a spectrum of colors, founding modern optics." },
    ],
    quotes: [{ text: '"If I have seen further, it is by standing on the shoulders of giants."', attribution: 'Isaac Newton', featured: true }],
    gallery: [
      { url: 'https://commons.wikimedia.org/wiki/Special:FilePath/Portrait%20of%20Sir%20Isaac%20Newton%2C%201689.jpg?width=700', alt: 'Portrait of Sir Isaac Newton by Godfrey Kneller, 1689' },
    ],
    facts: [
      { summary: 'He served as Master of the Royal Mint.', expand: 'Later in life, Newton took a government role overseeing England\'s currency, pursuing counterfeiters with the same rigor he applied to physics.' },
      { summary: 'He developed calculus independently of Leibniz.', expand: 'Newton and German mathematician Gottfried Wilhelm Leibniz developed calculus independently around the same time, leading to a famous and bitter priority dispute.' },
      { summary: 'He was deeply engaged in alchemy and theology.', expand: 'Alongside his scientific work, Newton wrote extensively on alchemy and biblical chronology — interests largely kept private during his lifetime.' },
    ],
    sources: [
      { name: 'The Royal Society', description: 'Historical archive and Principia records' },
      { name: 'Trinity College, Cambridge', description: 'Academic and biographical archive' },
      { name: 'Royal Collection Trust', description: 'Portrait provenance record' },
    ],
    seo: { metaTitle: 'Isaac Newton | LifeLegends', metaDescription: 'Discover the life of Isaac Newton, father of classical mechanics.', canonicalPath: '/legends/newton', ogImage: `${SITE_URL}/og/newton.jpg` },
  },
  {
    slug: 'lovelace',
    name: 'Ada Lovelace',
    roles: ['Mathematician', 'Writer', 'Programmer'],
    birthYear: 1815,
    deathYear: 1852,
    nationality: 'English',
    profession: 'Mathematician & Writer',
    tagline: '"That brain of mine is something more than merely mortal."',
    intro: "The daughter of the poet Lord Byron, Ada Lovelace worked with Charles Babbage on his proposed Analytical Engine and wrote what is widely considered the first algorithm intended for machine computation.",
    heroImage: 'https://commons.wikimedia.org/wiki/Special:FilePath/Ada%20Lovelace%20portrait.jpg?width=1400',
    thumbnail: 'https://commons.wikimedia.org/wiki/Special:FilePath/Ada%20Lovelace%20portrait.jpg?width=600',
    categorySlug: 'inventors',
    featured: false,
    viewCount: 13700,
    status: 'published',
    overviewTitle: 'The First Computer Programmer',
    overview: [
      'Born in 1815, Augusta Ada Byron was the only legitimate child of the poet Lord Byron, though her mother ensured she was raised with a rigorous education in mathematics and science, partly to steer her away from her father\'s perceived instability.',
      "As Countess of Lovelace, Ada developed a close working relationship with inventor Charles Babbage, translating an Italian paper on his proposed Analytical Engine and appending extensive notes of her own — notes that grew longer than the original article.",
      "Within those notes, Lovelace described an algorithm for the Analytical Engine to compute Bernoulli numbers, now widely regarded as the first published computer program, decades before any such machine was ever built.",
    ],
    stats: [
      { value: 1843, label: 'Notes Published' }, { value: 1, label: 'First Algorithm' },
      { value: 1980, label: "Ada Language Named For Her" }, { value: '∞', label: 'Impact' },
    ],
    timeline: [
      { year: 1815, title: 'Born in London', description: "Born Augusta Ada Byron, daughter of the poet Lord Byron and Anne Isabella Milbanke." },
      { year: 1833, title: 'Meets Charles Babbage', description: "Is introduced to Babbage and his early mechanical calculating engine, sparking a lifelong collaboration." },
      { year: 1835, title: 'Marries and Becomes Countess of Lovelace', description: 'Marries William King, who later becomes Earl of Lovelace, giving her the title by which she is remembered.' },
      { year: 1843, title: 'Publishes Her Notes', description: "Publishes translated notes on Babbage's Analytical Engine, including an algorithm to compute Bernoulli numbers." },
      { year: 1852, title: 'Passes Away in London', description: 'Dies at age 36, and is buried, at her request, next to her father Lord Byron.' },
      { year: 1980, title: 'The Ada Programming Language', description: 'The U.S. Department of Defense names a programming language "Ada" in her honor.' },
    ],
    achievements: [
      { counter: 1843, title: "First Published Algorithm", description: "Described a method for the Analytical Engine to compute Bernoulli numbers." },
      { counter: 'Ada', title: 'Programming Language Namesake', description: 'A major programming language was named in her honor in 1980.' },
      { counter: 'Vision', title: 'Beyond Calculation', description: 'Foresaw that computing machines could manipulate symbols and create music or art, not just numbers.' },
    ],
    quotes: [{ text: '"That brain of mine is something more than merely mortal."', attribution: 'Ada Lovelace', featured: true }],
    gallery: [
      { url: 'https://commons.wikimedia.org/wiki/Special:FilePath/Ada%20Lovelace%20portrait.jpg?width=700', alt: 'Ada Lovelace, watercolor portrait by Alfred Edward Chalon' },
    ],
    facts: [
      { summary: "Her mother pushed her toward mathematics to avoid her father's fate.", expand: "Fearing Ada would inherit her father Lord Byron's volatile temperament, her mother ensured she received a rigorous education emphasizing logic and mathematics from an early age." },
      { summary: 'She foresaw computers doing more than arithmetic.', expand: 'In her notes, Lovelace speculated that the Analytical Engine could one day compose music or create graphics, envisioning general-purpose computing generations before it existed.' },
      { summary: 'A major programming language is named after her.', expand: 'In 1980, the United States Department of Defense named its newly standardized programming language "Ada" in recognition of her contributions.' },
    ],
    sources: [
      { name: 'Bodleian Library, Oxford', description: "Lovelace-Babbage correspondence archive" },
      { name: 'Science Museum, London', description: 'Analytical Engine historical collection' },
      { name: 'Government Art Collection, UK', description: 'Portrait provenance record' },
    ],
    seo: { metaTitle: 'Ada Lovelace | LifeLegends', metaDescription: 'Discover the life of Ada Lovelace, the first computer programmer.', canonicalPath: '/legends/lovelace', ogImage: `${SITE_URL}/og/lovelace.jpg` },
  },
];
